/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.koocode.android.titanium;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.kroll.KrollCallback;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;

import java.util.HashMap;

@Kroll.module(name="Koocodetest", id="com.koocode.android.titanium")
public class KoocodetestModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "KoocodetestModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public KoocodetestModule(TiContext tiContext) {
		super(tiContext);
	}

  @Kroll.method
	public String example() {
    Log.d(LCAT, "example called");
    return "hello koocode user by module";
  }

	// Methods
	@Kroll.method
	public void testMethod(final Object[] args) {
		Log.d(LCAT, "testMethod called");
    final KrollDict options = (KrollDict) args[0];
    final KrollCallback successCallback = getCallback(options, "success");
    //final KrollCallback cancelCallback = getCallback(options, "cancel");
    //final KrollCallback errorCallback = getCallback(options, "error");
    final KrollDict dict = new KrollDict();
    dict.put("result", "myresult");
    Log.d(LCAT, "before callback");
    successCallback.callAsync(dict);
    Log.d(LCAT, "after callback");
	}
	
	// Properties
	@Kroll.getProperty
	public String getExampleProp() {
		Log.d(LCAT, "get example property");
		return "hello world";
	}
	
	
	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(LCAT, "set example property: " + value);
	}

  private KrollCallback getCallback(final KrollDict options, final String name) {
    if (options.containsKey(name)) {
      return (KrollCallback) options.get(name);
    } else {
      Log.d(LCAT, "Callback not found: " + name);
      return null;
    }
  }
}
